version: '3'

services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: localhost
    network_mode: host
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    network_mode: host
    ports:
      - 9000:9000
  angular-app:
    build: ./angular-app
    image: angular-app
    container_name: angular-app
    network_mode: host
  micronaut-app:
    build: ./micronaut-app
    image: micronaut-app
    container_name: micronaut-app
    network_mode: host